name: V_crypto

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: install V
      run: |
        git clone https://github.com/vlang/v
        cd v
        .\make.bat -tcc
    - name: test algorithms
      run: ./v/v test md4/ tea/ xtea/ _cipher/